apiVersion: v1
kind: Service
metadata:
   name: pythontest-service-lb
   labels:
      app: pythomtest
	  tier: frontend   
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8800
  selector:
    app: pythontest
	tier: frontend
 
