apiVersion: v1
kind: Service
metadata:
  name: pythontest-service-lb
  labels:
    app: pythomtest-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8800
  selector:
    app: pythontest-app
    tier: frontend
 
